<a href="https://colab.research.google.com/github/lalaggv2/CAD/blob/master/matplotlib_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><a name="mat"></a></p>

# **Matplotlib**

Matplotlib es una herramienta para visualización de datos en Python, construida sobre arreglos de NumPy.

Para todas las visualizaciones con Matplotlib, comenzamos creando una figura y un eje o conjunto de ejes. Una visualización típica es de la siguiente forma:

<p><img alt="Colaboratory logo" height="300px" src="https://i.imgur.com/CN4dd50.jpg" align="left" hspace="10px" vspace="0px"></p>

En esta imagen vemos cómo hemos generado 4 sencillas gráficas dispuestas en una matriz de 2x2. El primero de los conceptos a tratar es el de figura (figure). Ésta es el espacio que abarca las cuatro gráficas y que, en este ejemplo, se muestra de color verdoso con un borde verde un poco más fuerte. Es decir, en la imagen anterior, la figura sería la siguiente:

<p><img alt="Colaboratory logo" height="200px" src="https://i.imgur.com/LzKT7CG.jpg" align="left" hspace="10px" vspace="0px"></p>

Dentro de la figura nos encontramos con las cuatro mencionadas gráficas, cada una de las cuales se ha creado sobre un *conjunto de ejes* (axes). Se muestran a continuación los cuatro conjuntos de ejes:

<p><img alt="Colaboratory logo" height="300px" src="https://i.imgur.com/9WmCGDP.jpg" align="left" hspace="10px" vspace="0px"></p>

Vemos que del concepto "ejes" representa características como el título de la gráfica, las marcas en los ejes (lo que en matplotlib se denominan ticks), etc.

Por último, dentro de cada conjunto de ejes encontramos lo llamamos gráfica (plot). Estas serían las cuatro gráficas generadas:

<p><img alt="Colaboratory logo" height="300px" src="https://i.imgur.com/kfaMZLp.jpg" align="left" hspace="10px" vspace="0px"></p>

En resumen, la *figura* puede considerarse como un contenedor único que contiene todos los objetos que representan los ejes, gráficos y etiquetas. Por otra parte, el *conjunto de ejes* es un cuadro delimitador con marcas y etiquetas, que eventualmente contendrá los elementos del gráfico que componen nuestra visualización.

<p><a name="fig"></a></p>

#  **Creando figuras y ejes**

Usaremos el submódulo `pyplot` de la librería para realizar nuestros gráficos:

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

Existen dos formas en que podemos crear figuras y ejes. La forma más simple se conoce como *interfaz tipo Matlab*, donde la figura y los ejes se crean automáticamente: cuando utilizamos la función `plt.plot` se generan una figura y un conjunto de ejes de forma implícita

La segunda forma utiliza un estilo de programación orientado a objetos: referenciamos la figura y los ejes mediante las variables `fig` y `ax` respectivamente, y serán métodos y atributos de estas variables los que nos permitan personalizar la visualización.

Una primera opción para crear la figura y los ejes es utilizar las funciones `plt.figure` y `plt.axes`, que nos devuelven una referencia de la figura y conjunto de ejes utilizados.

<p><a name="per"></a></p>

# **Personalización básica del gráfico**

* **Estilo MATLAB**

La función `plt.plot` realiza por defecto un gráfico de línea. Podemos personalizar el color, el estilo y el marcador de la línea mediante los argumentos por palabra clave `color`, `linestyle` y `marker`, respectivamente. E

En el caso del color, podemos pasar este de forma completa o abreviada:

>
    COM       ABR
    blue ---- b
    green --- g
    red ----- r
    cyan ---- c
    magenta - m
    yellow -- y  
    black --- k
    white --- w

De forma similar, podemos pasar el estilo de la línea de forma completa o abreviada:
>
    COM        ABR      DESCRIPCIÓN
    solid ---- "-" ---- línea sólida
    dashed --- "--" --- línea discontinua
    dashdot -- "-." --- línea discontinua+punto
    dotted --- ":" ---- línea punteada  

Y finalmente, para el marcador, algunas opciones son:
>   

    "o" ------ círculo
    "^" ------ triángulo
    "p" ------ pentágono
    "h" ------ hexágono
    "s" ------ cuadrado
    "|" ------ línea vertical
    "_" ------ línea horizontal
    "+" ------ más
    "x" ------ equis

Podemos agregar al gráfico un título y etiquetas para los ejes $x$ y $y$, con los métodos `plt.title`, `plt.xlabel` y `plt.xylabel`, respectivamente:

Ahora, para definir los límites de los ejes tenemos dos opciones. La primera es utilizando los métodos `plt.xlim` y `plt.ylim`. Alternativamente, el método `plt.axis`, con el cual podemos especificar los límites de los ejes pasando una lista que contiene como elementos los límites de la siguiente manera:
>
    plt.axis([xmin, xmax, ymin, ymax])

Podemos además especificar, mediante el argumento por palabra clave `loc`, la posición de la leyenda dentro del gráfico. Por defecto, se utiliza la "mejor" posición (best). Las opciones disponibles son:
>
    POSICIÓN        DESCRIPCIÓN
    best ---------- mejor
    upper right --- sup der
    upper left ---- sup izq
    lower left ---- inf izq
    lower right --- inf der
    right --------- der
    center left --- centro izq
    center right -- cento der
    lower center -- inf central
    upper center -- sup central
    center -------- central

* **Estilo orientado a objetos**

Si bien la mayoría de las funciones en `plt` se traducen directamente a métodos `ax` (como `plt.plot()` → `ax.plot()`, `plt.legend()` → `ax.legend()`, etc.), este no es el caso para todos los comandos. En particular, las funciones para establecer límites, etiquetas y títulos se modifican ligeramente. Para realizar la transición entre las funciones de estilo MATLAB y los métodos orientados a objetos, realizamos los siguientes cambios (Puede consultar todos los atributos y métodos de la clase `axes` en este [link](https://matplotlib.org/3.1.1/api/axes_api.html#array)):

* `plt.plot()`   → `ax.plot()`
* `plt.legend()` → `ax.legend()`
* `plt.axis()`   → `ax.axis()`

* `plt.xlabel()` → `ax.set_xlabel()`
* `plt.ylabel()` → `ax.set_ylabel()`
* `plt.xlim()`   → `ax.set_xlim()`
* `plt.ylim()`   → `ax.set_ylim()`
* `plt.title()`  → `ax.set_title()`

Realicemos la misma gráfica anterior en el estilo orientado a objetos:

<p><a name="sty"></a></p>

# **Cambiando el estilo de graficación**

Ya vimos el estilo de graficación estándar que se tiene en `matplotlib.pyplot`.

Una personalización del fondo (y otras características del gráfico) requiere la especificación de la figura. Sin embargo, podemos utilizar la directiva `plt.style` para elegir diferentes estilos para nuestras figuras.

Mediante el atributo `plt.style.available` podemos acceder a los diferentes estilos disponibles:

In [ ]:
plt.style.available

['Solarize_Light2',
 '_classic_test_patch',
 '_mpl-gallery',
 '_mpl-gallery-nogrid',
 'bmh',
 'classic',
 'dark_background',
 'fast',
 'fivethirtyeight',
 'ggplot',
 'grayscale',
 'petroff10',
 'seaborn-v0_8',
 'seaborn-v0_8-bright',
 'seaborn-v0_8-colorblind',
 'seaborn-v0_8-dark',
 'seaborn-v0_8-dark-palette',
 'seaborn-v0_8-darkgrid',
 'seaborn-v0_8-deep',
 'seaborn-v0_8-muted',
 'seaborn-v0_8-notebook',
 'seaborn-v0_8-paper',
 'seaborn-v0_8-pastel',
 'seaborn-v0_8-poster',
 'seaborn-v0_8-talk',
 'seaborn-v0_8-ticks',
 'seaborn-v0_8-white',
 'seaborn-v0_8-whitegrid',
 'tableau-colorblind10']

Podemos elegir alguno de estos estilos utilizando el método `plt.style.use`:

<p><a name="mul"></a></p>

# **Creando mútiples gráficos**

Para la generación de la figura y de uno o más conjuntos de ejes podemos recurrir a la función `plt.subplots`, la cual crea estos objetos y devuelve una referencia a la figura y al conjunto de ejes (si solo se ha creado uno) o a una lista de referencias a los conjuntos de ejes (si se han creado dos o más).

Como ya vimos, la función `plt.subplots` crea por defecto una figura y un solo eje. Para tener dos gráficos en el mismo eje utilizamos la función `ax.plot` reiteradamente:

Si queremos especificar el número de ejes a usar, debemos hacerlo explícitamente en la función `plt.subplots`. Sus dos primeros argumentos representan el número de filas y columnas a utilizar, solo que en este caso la referencia a las figuras se hace mediante `ax`:

Otros argumentos por palabra clave útiles de la función `plt.subplots`, son `sharex` y `sharey`, que nos permiten compartir los ejes $x$ y $y$, respectivamente, entre las diferentes gráficas.

recuerde consultar la documentación de la función `plt.subplots` para obtener más información respecto a los argumentos disponibles de la función.

Finalmente, podemos añadir un título a la figura con el método `suptitle` del objeto `fig`:

<p><a name="sea"></a></p>

# **Seaborn**

Existen otros múltiples tipos de gráficos como los son

- Bar Graph
- Pie Chart
- Box Plot
- Line Chart and Subplots
- Heat maps
- Histograms

Entre otros, y su implementación no dista mucho de lo ya discutido. Sin embargo existen formas más sencillas de implementar muchas de estas gráficas. Con el fin de visualizarlo de una forma amigable partiremos de un ejemplo con datos de la nba

In [ ]:
nba = pd.read_csv("https://raw.githubusercontent.com/tomasate/Datos_Clases/main/Datos_1/nba.csv", index_col="Unnamed: 0")
nba.dropna(inplace=True)
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0

Acontinuación  responderemos las siguientes preguntas y veremos las respuestas en calidad de imagen.
* ¿Cuáles son los cinco equipos que pagan los salarios mas altos? (sumando toda la nómina de sus jugadores).

In [ ]:
team_salary = nba.groupby('Team', as_index=False)['Salary'].sum().sort_values(by = 'Salary', ascending = False)[:5]

#team_salary = nba.groupby('Team', as_index=False)['Salary'].sum().sort_values(by = 'Salary', ascending = False)[:5]
team_salary

                     Team      Salary
12   Los Angeles Clippers  93906914.0
20  Oklahoma City Thunder  81515298.0
9   Golden State Warriors  80535517.0
5     Cleveland Cavaliers  74068189.0
4           Chicago Bulls  73265800.0

* Separe la variable *Age* en tres grupos y cree una nueva columna llamada *Age-Group* con esta información. Muestre un gráfico de barras con el número de jugadores por grupo de edad diferenciando en esta (mediante un código de color) la posición.

* Construya dos gráficos de caja en los que se muestren los salarios vs las posiciones de los jugadores y salarios vs grupo de edad en la misma figura, de manera que compartan el eje del salario. ¿Cuál característica es más importante a la hora de definir el salario?

* Construya una tabla dinámica que muestre el salario promedio de los jugadores por equipo y posición para para los cinco equipos que pagan mejores salarios. Visualice este resultado mediante un mapa de calor.

Una tabla dinámica en síntesis es una forma de resumir la información de manera númeríca no visual(no con gráficos ni animaciónes). Permite ver comparaciones, patrones y tendencias en ellos. En pandas es fácil hacerlas con el método `pivot_table` de los `DataFrames`

En este caso hemos hecho una agrupación según la Posición y el equipo, aplicando la media como operación de agregación.

## Tipos de graficos

**¿Qué es un histograma?**

Es un gráfico que muestra cómo se distribuyen
los valores de una variable numérica
dividiéndolos en "rangos" o "intervalos", en
lugar de mostrar cada valor individual, agrupa
los datos en bloques y cuenta cuántos valores
caen dentro de cada rango.

**¿Cuándo usarlo?**

Cuando necesitas ver la forma de una variable
numérica: si es simétrica, sesgada,
concentrada, dispersa, etc.

##Seaborn datasets
Seaborn dispone de datasets ya incorporados que podemos importar sin necesidad de cargarlos desde archivos. Cómo ejemplo, cargaremos en esta ocasión el dataset `iris` directamente desde `seaborn`.

In [ ]:
iris = sns.load_dataset('iris')

## ¿Qué es un boxplot?
Un boxplot (o diagrama de caja) es un gráfico
estadístico que resume una variable numérica
usando cinco valores clave:
* **Mínimo** (sin contar outliers)
* **Primer cuartil (Q1)** – 25% más bajo
* **Mediana (Q2)** – valor central
* **Tercer cuartil (Q3)** – 75% más bajo
* **Máximo** (sin contar outliers)

¿Qué permite ver?
* Si los datos están concentrados o dispersos
* Si hay valores extremos (outliers)
* Si los datos están simétricos o sesgados
* La posición de la mediana respecto a los
cuartile

## ¿Qué es un gráfico de barras?
Es un gráfico que muestra la frecuencia o
cantidad asociada a cada categoría de una
variable categórica, cada barra representa una
categoría, y su altura representa el número de
veces que aparece en los datos.

**¿Cuándo usarlo?**

Cuando tienes una variable categórica y quieres
visualizar su comportamiento.

**¿Qué permite ver?**

* La categoría que más aparece
* Categoría que tienen pocos datos
* Si existen clases desbalanceadas
* Si alguna categoría domina el conjunto de
datos

## ¿Qué es un pie chart?
Es un gráfico que representa proporciones de
un total, donde cada categoría se muestra
como una “rebanada” de un círculo, todo el
gráfico suma el 100%.

**¿Cuándo usarlo?**
* Para mostrar la proporción relativa de cada
categoría.
* No recomendado cuando hay muchas
categorías.
**¿Qué permite ver?**
* Qué categoría tiene la mayor proporción
* Si una categoría domina claramente
* Cómo se reparte el total entre las partes

## ¿Qué es un violin plot?
Un violin plot muestra la distribución de una
variable numérica, también incluye una curva
de densidad que representa la frecuencia de
los valores. La forma del “violín” indica dónde
se concentran más los datos.

**¿Cuándo usarlo?**
* Cuando el boxplot es insuficiente para
entender la forma de la distribución.
* Ideal para comparar una variable numérica
entre diferentes categorías

**¿Qué permite ver?**
* Si los datos están concentrados o dispersos
* Si hay una o varias modas (picos de densidad)
* La asimetría en la distribución
* Outliers y mediana

## ¿Qué es un scatterplot?

Un scatterplot muestra una nube de puntos en
un plano, donde:
* El eje X representa una variable numérica.
* El eje Y representa otra variable numérica.
* Cada punto es una observación del conjunto
de datos.
Sirve para detectar relaciones o patrones entre
dos variables.

**¿Qué permite ver?**
* Si dos variables se relacionan entre sí
* Qué tan fuerte o débil es esa relación
* Si hay grupos separados
* Si hay valores atípicos que no siguen la
tendencia

## ¿Qué es un line plot?
Es un gráfico que conecta puntos de datos con
líneas, para mostrar cómo cambia una variable
numérica en función de otra variable,
normalmente tiempo (fecha, año, trimestre,
etc.).

**¿Cuándo usarlo?**
* Analizar tendencias
* Ver fluctuaciones o estacionalidades
* Comparar antes y después de un evento

**¿Qué permite ver?**
* Si hay una tendencia creciente o decreciente
* Picos o caídas abruptas
* Estabilidad o variabilidad en el tiempo
* Posibles ciclos o patrones repetitivos

## ¿Qué es un heatmap de correlación?
Es una matriz visual donde cada celda
representa el coeficiente de correlación entre
dos variables numéricas, el color indica la
fuerza y dirección de la relación:
*  +1: correlación positiva perfecta (ambas
suben o bajan juntas)
*  0: sin relación lineal
*  −1: correlación negativa perfecta (una sube, la
otra baja)
**¿Qué permite ver?**
* Si hay variables que aumentan o disminuyen
juntas
* Posibles multicolinealidades (útil para
regresiones)
* Dónde hay relaciones débiles o irrelevantes
* Evitar redundancias en modelado
* Identificar relaciones inesperadas

## ¿Qué es un pairplot?
Genera una cuadrícula de gráficos con todas
las combinaciones posibles entre variables
numéricas de un DataFrame:
* Las diagonales muestran la distribución
univariada de cada variable (histograma o
kde).
* Las celdas fuera de la diagonal muestran
gráficos de dispersión entre pares de
variables.
* Puede incluir colores por categoría si se añade
una variable categórica (ideal para clasificar o
segmentar).

**¿Qué permite ver?**
*  Relaciones lineales o no lineales entre pares
de variables
* Variables que se comportan de forma similar
* Agrupamientos de datos (especialmente si se
usa hue)
* Outliers o valores extremos que se repiten
entre pares

**¿Qué es FacetGrid?**
Es una técnica que permite dividir un gráfico
en múltiples subgráficos, cada uno
correspondiente a un subgrupo de una variable
categórica.
Con FacetGrid, puedes ver cómo cambia la
relación o distribución de variables según
diferentes categorías.

**¿Qué permite ver?**
* Cambios de patrón entre categorías.
* Similitudes o diferencias visuales entre
subgrupos.
* Agrupamientos, outliers o relaciones
específicas de un grupo.